export const products = [
  {
    _id: "1",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  { _id: "2", name: "12 kg tup", category: { _id: "1", name: "Tup" }, sPrice: 100, pPrice: 120, active: true },
  { _id: "3", name: "24 kg tup", category: { _id: "1", name: "Tup" }, sPrice: 100, pPrice: 120, active: true },
  { _id: "4", name: "12'lik klima", category: { _id: "1", name: "Tup" }, sPrice: 100, pPrice: 120, active: true },
  { _id: "5", name: "12'lik klima", category: { _id: "1", name: "Tup" }, sPrice: 100, pPrice: 120, active: true },
  {
    _id: "6",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "7",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "8",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "9",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "0",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "11",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "12",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "13",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "14",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "15",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "16",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "17",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "18",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "19",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
  {
    _id: "20",
    name: "12'lik klima",
    category: { _id: "1", name: "Beyaz Eşya" },
    sPrice: 100,
    pPrice: 120,
    active: true,
  },
];
